apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:1.22.0-alpine
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: myapp-env
              key: API_KEY
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myapp-cache
          mountPath: /var/cache/nginx
        - name: myapp-run
          mountPath: /var/run
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
      volumes:
      - name: myapp-cache
        emptyDir: {}
      - name: myapp-run
        emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
